config/routes.rb
Rails.application.routes.draw do
  root 'chats#index'
  
  resources :chats  do
  
    collection do
      post :confirm
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
validates :username, presence: true
validates :mail, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#     config.time_zone = 'Tokyo'
# config.active_record.default_timezone = :local
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats =Chat.all
  end
def show
  @chats =Chat.find(params[:id])
end
def new
  if params[:back]
    @chats=Chat.new(chat_params)
  else
  @chats=Chat.new
  end
end
def create
  @chats =Chat.new(chat_params)
  if( @chats.save)
    redirect_to chats_path
  else
    render :new
  end
end

def destroy
  @chats =Chat.find(params[:id])
  @chats.destroy
  redirect_to chats_path
end

def edit
  @chats=Chat.find(params[:id])
end
def update
  @chats =Chat.find(params[:id])
  if(@chats.update(chat_params))
    redirect_to chats_path
  else
    render :edit
  end
end
def confirm
  @chats=Chat.new(chat_params)
  render :new if @chats.invalid?
end

private
def chat_params
  params.require(:chat).permit(:username, :mail)

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/confirm.html.erb
<!DOCTYPE html>
<html>
<head> 
<meta charset="UTF-8"></head>
<title> Welcome to my TweetTrone</title>
<body>
    <header class="header">
        <nav class="navbar">
            <ul class="nav-item">
              <li class="item"><%= link_to "Home", chats_path %></li>
                <li class="item"><%= link_to "New Tweet", new_chat_path %></li>
                
            </ul>
        </nav>
        <header>
<div class="container">
<h1> Check before submit</h1>

 <%= form_with(model: @chats, url: new_chat_path, local: true) do |f| %>
<%= form_for @chats do |f| %>
  <%= f.hidden_field :username %>
  <%= f.hidden_field :mail %>

  <p>Username:<%= @chats.username %></p>
  <p>Mail:<%= @chats.mail %></p>
  <%= f.submit  "submit" %>
<% end %>

<%= form_with(model: @chats, url: chats_path, local: true) do |f| %>
  <%= f.hidden_field :username %>
  <%= f.hidden_field :mail %>
  <%= f.submit "back", name: 'back' %>
<% end %>
<% end %>
<footer class="footer">
        <p class="foot-content"> <i>Copyright &copy; 2019 Armel NIZIGIYIMANA</i></p>

    </footer>


</body>
</html>

app/views/chats/edit.html.erb
<!DOCTYPE html>
<html>
<head> 
<meta charset="UTF-8"></head>
<title> Welcome to my TweetTrone</title>
<body>
    <header class="header">
        <nav class="navbar">
            <ul class="nav-item">
                <li class="item"><a href="#">Home</a></li>
                <li class="item"><%= link_to "New Tweet", new_chat_path %></li>
                
            </ul>
        </nav>
        <header>
<div class="container">
<h1> change post</h1>
<%= form_for @chats do |f| %>
    <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>
    <div>
    <%= f.label :mail %>
    <%= f.text_area :mail %>
    </div>

<%= f.submit 'update Post' %>
</div>
    <% end %>
    </div>
<footer class="footer">
        <p class="foot-content"> <i>Copyright &copy; 2019 Armel NIZIGIYIMANA</i></p>

    </footer>


</body>
</html>

app/views/chats/form.html.erb
<%= form_for @chat do |f| %>
    <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>
    <div>
    <%= f.label :mail %>
    <%= f.text_field :mail %>
    </div>

<%= f.submit %>
</div>
    <% end %>

app/views/chats/index.html.erb
<!DOCTYPE html>
<html>
<head> 
<meta charset="UTF-8"></head>
<title> Welcome to my TweetTrone</title>
<body>
    <header class="header">
        <nav class="navbar">
            <ul class="nav-item">
                <li class="item"><%= link_to "Home", chats_path %></li>
                <li class="item"><%= link_to "New Tweet", new_chat_path %></li>
                
            </ul>
        </nav>
        <header>
<div class="container">
<h1>Chats</h1>

<% @chats.each do |chat| %>
  <p class="username"><%= chat.username %>: </p>  
  <p> =><%= chat.mail %> </p>
  <p>   created on: <%= chat.created_at %> </p>
  <p>  updated on: <%= chat.updated_at %> </p>
    <%= link_to "New", new_chat_path %>
    
    <%= link_to "Edit", edit_chat_path(chat) %>

   
     <%= link_to "Delete", chat, method: :delete, data: { confirm: "Are you sure you want to delete this this chat?"} %>
<p class="mail"></p>
<% end %>

</div>
<footer class="footer">
        <p class="foot-content"> <i>Copyright &copy; 2019 Armel NIZIGIYIMANA</i></p>

    </footer>


</body>
</html>

app/views/chats/new.html.erb
<!DOCTYPE html>
<html>
<head> 
<meta charset="UTF-8"></head>
<title> Welcome to my TweetTrone</title>
<body>
    <header class="header">
        <nav class="navbar">
            <ul class="nav-item">
            <li class="item"><%= link_to "Home", chats_path %></li>
                <li class="item"><%= link_to "New Tweet", new_chat_path %></li>
                
            </ul>
        </nav>
        <header>
<div class="container">

<h1> chat now</h1>

<%= form_with(model: @chats, url: confirm_chats_path, local: true) do |f| %>
    <% if @chats.errors.any? %>
    <div id="error_explanation">
      <h2><%= @chats.errors.count %>errors occurred.</h2>
      <ul>

      <% @chats.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>
    <div>
    <%= f.label :mail%>
    <%= f.text_area :mail %>
    </div>

<%= f.submit 'Post' %>
</div>
    
    <% end %>
    </div>
<footer class="footer">
        <p class="foot-content"> <i>Copyright &copy; 2019 Armel NIZIGIYIMANA</i></p>

    </footer>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>